spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myshop?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: user-web

server:
  port: 8049
  servlet:
    context-path: /

logging:
  level:
    tk:
      mybatis: trace

rocketmq:
  name-server: 10.4.188.185:9876;
  producer:
    group: orderProducerGroup

